Задача 3.1.2 Task7
itmShashikhinVasiliy/Task-7 pull request #1
Opened 2024-09-13 19:34 UTC by shashikhin

2024-09-13 20:10 UTC, pdasilem requested changes

2024-09-13 20:10 UTC, pdasilem commented on src/main/java/ru/shashikhin/spring/boot_security/web/services/UserServiceImpl.java
> +            Hibernate.initialize(user.getRoles());
не надо второй раз инициализировать контекст хибера

2024-09-13 20:10 UTC, pdasilem commented on src/main/java/ru/shashikhin/spring/boot_security/web/util/UserValidator.java
> +            && !Thread.currentThread().getStackTrace()[2].getMethodName().equals("update")) {
плохой вариант так дергать тред

2024-09-13 21:31 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/services/UserServiceImpl.java
> +            Hibernate.initialize(user.getRoles());
LazyInitializationException: failed to lazily initialize a collection of roles, could not initialize proxy - no Session была ошибка
Поменял fetchType у User с LAZY на EAGER (у many-to-many с ролями). Как я понимаю если это нужно для пользователей, а ролей не так много, то ещё позволительно. Но нормального решения как в many-to-many использовать fetchType=LAZY не нашёл

2024-09-13 21:32 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/util/UserValidator.java
> +            && !Thread.currentThread().getStackTrace()[2].getMethodName().equals("update")) {
Убрал проверку создан ли пользователь или нет в метод сервиса по его созданию. Так как validate пользуется ещё для редактирования

2024-09-13 22:57 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/services/UserServiceImpl.java
> +            Hibernate.initialize(user.getRoles());
LazyInitializationException: failed to lazily initialize a collection of roles, could not initialize proxy - no Session 
была ошибка
Поменял fetchType у User с LAZY на EAGER (у many-to-many с ролями). Как я понимаю если это нужно для пользователей, а ролей не так много, то это ещё позволительно. Но нормального решения как в many-to-many использовать fetchType=LAZY не нашёл

2024-09-13 22:58 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/util/UserValidator.java
> +            && !Thread.currentThread().getStackTrace()[2].getMethodName().equals("update")) {
Убрал данную строку. В edit просто не вызываю validate, оставил его только для проверки при создании пользователя

2024-09-15 14:52 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/services/UserServiceImpl.java
> +            Hibernate.initialize(user.getRoles());
https://www.matheusmello.io/posts/java-how-to-fix-hibernate-lazyinitializationexception-failed-to-lazily-initialize-a вот допустим здесь 3 решения. Из которых предлагают: сделать Eager, либо также Hibernate.initialize, либо самому писать запрос

2024-09-15 21:12 UTC, pdasilem requested changes

2024-09-15 21:12 UTC, pdasilem commented on src/main/java/ru/shashikhin/spring/boot_security/web/models/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
это плохой вариант.
жадная загрузка - зло.
попробуй транзакшнел ли джоин фетч в запросе

2024-09-15 21:12 UTC, pdasilem commented on src/main/java/ru/shashikhin/spring/boot_security/web/services/RegistrationServiceImpl.java
> +            user.setRoles(Collections.singleton(roleService.findByName("ROLE_USER")));
правильнее будет вернуть управление пользователю с ошибкой - роль не установлена

2024-09-15 21:45 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/services/RegistrationServiceImpl.java
> +            user.setRoles(Collections.singleton(roleService.findByName("ROLE_USER")));
Я думаю просто убрать проверку на 28 строке. Так как register у меня используется только в двух местах создания пользователя (AdminController и AuthController), перед этим я проверяю что пользователя не существует. Так что тут, при создании точно у него не будет роли и я провожу такую инициализацию здесь, добавляя ему роль ROLE_USER

2024-09-15 22:14 UTC, shashikhin commented on src/main/java/ru/shashikhin/spring/boot_security/web/models/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
Не до конца понял предложение: 
> попробуй транзакшнел ли джоин фетч в запросе
Почитал в интернете про эту ошибку ещё. Пишут что сессия открывается только для объекта (в моем случае) User, для множества roles (Role) не открывается.
Написал запрос findByUsernameAndFetchLazyRelationEagerly где я выполняю JOIN FETCH для получения ролей (в репозитории UserRepository) и использую его только для этого метода loadUserByUsername. Насколько я понимаю далее roles будут подтягиваться с fetchType.LAZY

2024-09-16 21:21 UTC, pdasilem approved these changes

2024-09-17 13:53 UTC, merged